name: Deploy VanDJsClub Frontend to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vandjs-fe-api"
          heroku_email: "andriikukharv@gmail.com"
          healthcheck: "https://vandjs-fe-api-0756fd312d48.herokuapp.com/"
